sudo: false
dist: trusty
language: cpp

addons: 
  apt: 
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libboost-test-dev

before_install:
  - eval "CC=gcc-7 && CXX=g++-7"

script:
  - cmake -D CMAKE_BUILD_TYPE=Debug .
  - cmake --build . -- -j2 
  - ctest -j2 --output-on-failure