language: cpp 
compiler: gcc
sudo: true

addons: 
  apt: 
    packages: 
      - libboost-all-dev
      - g++-7
    
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov

install: 
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90

before_script: 
  - mkdir build 
  - cd build 
  - cmake ..

script: 
  - export CC=gcc-7
  - export CXX=g++-7
  - make

after_success:
  - ../get_code_cov.sh
  - codecov
