sudo: false
dist: trusty
language: cpp
  
addons: 
  apt: 
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libboost-all-dev
      - lcov

before_install:
  - eval "CC=gcc-7 && CXX=g++-7"

script:
  - cmake -D Template_ENABLE_COVERAGE:BOOL=TRUE
          -D CMAKE_BUILD_TYPE=Debug .
  - cmake --build . -- -j2 
  - ctest -j2 --output-on-failure

after_success:
  # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info 
  # debug info
  - lcov --list coverage.info 
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"
