language: cpp 

compiler: gcc 

install:
# Boost
  - sudo apt install -qq libboost-all-dev
# Codecov
  - sudo pip install codecov

before_script: 
  - mkdir build 
  - cd build 
  - cmake ..

script: 
  - make && make test
# Get code coverage
  - ./get_code_cov
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
