sudo: false
dist: trusty
language: cpp
  
cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

addons: 
  apt: 
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - libboost-test-dev
      - lcov

before_install:
  - eval "CC=gcc-7 && CXX=g++-7"

install:
# (fake) install dependencies (usually involves wget, configure, make, ...)
# install into cache folder (build binaries+headers only, no sources and do NOT build there)
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydependency.so

script:
  - cmake -D Template_ENABLE_COVERAGE:BOOL=TRUE
          -D CMAKE_BUILD_TYPE=Debug .
  - cmake --build . -- -j2 
  - ctest -j2 --output-on-failure

after_success:
  # Create lcov report
  # capture coverage info
  - lcov --directory . --capture --output-file coverage.info
  # filter out system and extra files.
  # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  # output coverage data for debugging (optional)
  - lcov --list coverage.info
  # Uploading to CodeCov
  # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
