language: cpp 
dist: xenial
compiler: gcc
sudo: true


addons: 
  apt: 
    packages: libboost-all-dev
    
before_install:
  - sudo pip install codecov

before_script: 
  - mkdir build 
  - cd build 
  - cmake ..

script: 
  - make && make test
# Get code coverage
  - ./get_code_cov
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
